### ISSUE TITLE
What is penalty / cooldown time for requesting under-walltime jobs?

### ISSUE THREAD

**Issue by dwinston** [dwinston/nugex#1]
Is there a difference between taking longer to start vs finishing early?

Story:
> my job style recently has been to run many small jobs… I requested 40 jobs the other day and they all started instantly, however the last few jobs had zero walltime because I ran out of fireworks, and then my next single job took ~2 days to start... not sure if that was just because of the overall state of the queue, or a result of the penalization algorithm

@mkhorton

**Comment by dwinston** [comment]
R. Gerber said that there is no automatic penalization at present for underutilizing requested walltime.

**Comment by mkhorton** [comment]
Thanks @dwinston ! Much obliged for the information
